language: php

php:
  - 5.3
  - 5.4

before_script:
  - mv ../cakephp-codesniffer ../cakephp_codesniffer && cd ../cakephp_codesniffer
  - composer selfupdate
  - composer update
  - phpenv rehash

script:
  - cd CakePHP && phpunit

notifications:
  email: false
